services:
  bot:
    environment:
      INSTAGRAM_COOKIES_FILE: /run/secrets/instagram-cookies.txt
    volumes:
      - type: bind
        source: ./secrets/instagram-cookies.txt
        target: /run/secrets/instagram-cookies.txt
        read_only: true
        bind:
          create_host_path: false
